# Generated by Django 3.0.3 on 2020-11-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoviesModel',
            fields=[
                ('title', models.CharField(max_length=210)),
                ('released_year', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('id', models.CharField(max_length=118, primary_key=True, serialize=False)),
                ('genres', models.CharField(max_length=118)),
            ],
        ),
    ]
