# Generated by Django 3.0.3 on 2020-11-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesmodel',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
